name: model workflow

on: 
  pull_request: 
    branches:
    - main
    - benchmark

jobs:
  my_job:
    name: validate model
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elainehu222/cpoptimizer:latest
      credentials:
        username: elainehu222
        password: ${{secrets.GHCR_TOKEN}}

    steps:
    - name: checkout tsnkit
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install seaborn

    - name: gurobi-license
      env: 
        GRB_LICENSE_FILE: ${{secrets.GUROBI_LICENSE}}
      run: |
        echo "$GRB_LICENSE_FILE" > $HOME/gurobi.lic
        echo "grb_license_file=$HOME/gurobi.lic" >> $GITHUB_OUTPUT
        
    - name: get changed models
      id: changes
      run: |
        cd $GITHUB_WORKSPACE
        changes=$(git diff --name-only HEAD^1)
        changed_models=$(echo $changes | grep "src/tsnkit/models/.*\.py$" | xargs -n1 basename | sed 's/\.py$//' | tr '\n' ' ')
        echo "models=$changed_models" >> "$GITHUB_OUTPUT"
        echo "$changed_models"

    - name: get git lfs
      run: |
        git lfs install
        git lfs pull
    
    - name: run test
      env: 
        GRB_LICENSE_FILE: ${{steps.gurobi-license.outputs.grb_license_file}}
      run: |
        python -m tsnkit.test.debug ${{steps.changes.outputs.models}} jrs_nw ls smt_wa --subset 
      
    
