name: workflow

on: 
  pull_request_target: 
    branches:
    - main
    - workflow

jobs:
  my_job:
    name: validate model
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elainehu222/cpoptimizer:latest
      credentials:
        username: elainehu222
        password: ${{secrets.GHCR_TOKEN}}

    steps:
    - name: checkout tsnkit
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: get changed algorithms
      id: changes
      env:
        PR: ${{github.event.pull_request.head.sha}}
        MAIN: ${{github.event.pull_request.base.sha}}
      run: |
        pip install -q -r requirements.txt
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        changes=$(git diff --name-only "$PR" "$MAIN")
        changed_models=$(echo "$changes" | grep '^tsnkit/algorithms/.*\.py$' | xargs -n1 basename | sed 's/\.py$//' | tr '\n' ' ')
        echo "models=$changed_models" >> "$GITHUB_OUTPUT"
        echo "$changed_models"
    
    - name: run test
      run: |
        python -m tsnkit.test.debug ${{steps.changes.outputs.models}} jrs_nw ls smt_wa --subset 
      
