name: model workflow

on: 
  pull_request: 
    branches:
    - main
    - benchmark

jobs:
  my_job:
    name: validate model
    runs-on: ubuntu-latest

    steps:
    - name: first step
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install seaborn

    - name: gurobi license
      env: 
        GRB_LICENSE_FILE: ${{secrets.GUROBI_LICENSE}}
      run: |
        cd opt
        cd gurobi
        echo "${{secrets.GUROBI_LICENSE}}" > gurobi.ilc
        cd ..
        cd ..
        
    - name: get changed models
      id: changes
      run: |
        changes=$(git diff --name-only HEAD^1 HEAD)
        changed_models=$(echo "$changed_files" | grep "./src/tsnkit/models/.*\.py$" | xargs -n1 basename | sed 's/\.py$//' | tr '\n' ' ')
        echo "models=$changed_models" >> "$GITHUB_OUTPUT"

    - name: get git lfs
      run: |
        git lfs install
        git lfs pull
    
    - name: run test
      run: |
        cd src
        python -m tsnkit.test.debug ${{steps.changes.outputs.models}} ls jrs_nw smt_wa --subset 
      
    
